# Generated by Django 3.2.8 on 2021-10-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date_aded',
            new_name='date_added',
        ),
    ]
